### ISSUE TITLE
Replication does not undelete documents

### ISSUE THREAD

**Issue by s-rogers** [redgeoff/replicate-couchdb-cluster#18]
Just a quick sanity check to make sure I understand the expected behaviour here.

1 - I replicate a cluster with 1 database with 2 documents in it 

At this point my backup cluster has the database with 2 documents in it

2 - I delete 1 document from my source database.

Lets say this was a mistake so I want to restore from backup.  

3 - I "restore" my source cluster by replicating my backup cluster with my source cluster.

A this point my database still has 1 document in it, despite the backup having 2.

Is this expected behaviour?  If so then am I misusing the tool to do a restore from backup?  How do you use this - do you simply change your applications to use the backup as their database rather than trying to restore the original?  Or is there some kind of option I am missing around undeleting deleted documents?

**Comment by redgeoff** [comment]
What you just described is the typical behavior with how CouchDB replicates documents. If you want to undelete a document then you'll need to do something like [this](https://stackoverflow.com/questions/11194149/how-can-i-undelete-a-set-of-documents-in-couchdb). CouchDB preserves deleted documents until the compaction routine runs.
