### ISSUE TITLE
Re-check database list before replication

### ISSUE THREAD

**Issue by s-rogers** [redgeoff/replicate-couchdb-cluster#25]
Would you be open to implementing, or accepting a PR which handles the problem of a database being deleted after the initial replication loop has started?  e.g. - checking for existence in the loop before we call replicate.

We are using this against a system where databases are created and deleted quite frequently, and we are hitting issues when long replication times mean that the initial db.all().each contains databases that have subsequently been deleted.  When it gets to replicating them an error is thrown which interrupts the whole backup.

**Comment by redgeoff** [comment]
Hi! Sure a PR that uses db.exists() to check the source DB would be pretty
cool

**Comment by TheSamSmith** [comment]
Hi, I've just been looking at implementing this. The tests appear to need a local database running, is this the case? If so how do I go about setting that up?

**Comment by redgeoff** [comment]
Cool! I've just merged https://github.com/redgeoff/replicate-couchdb-cluster/pull/26 that makes the testing a little easier. You'll want to merge master into your branch.

For more info on setting up CouchDB locally, please see [Set up a dev env](https://github.com/redgeoff/replicate-couchdb-cluster/blob/master/TESTING.md#set-up-dev-enviornment)

**Comment by redgeoff** [comment]
Implemented by https://github.com/redgeoff/replicate-couchdb-cluster/pull/31
