### ISSUE TITLE
Example for Cloudant?

### ISSUE THREAD

**Issue by peteruithoven** [redgeoff/replicate-couchdb-cluster#6]
Any chance you could add an example for usage with Cloudant? 
I can't get it to work, I'm afraid I'm doing something wrong.

I'm creating the source and target url's using environment variables:
```
export DB_HOST=peteruithoven.cloudant.com
export DB_USER=peteruithoven
export DB_PASS='mypassword'
export DB_URL='https://'$DB_USER:$DB_PASS@$DB_HOST

export DB_HOST2=85debada-fc80-4597-a913-ad1b699c3a5c-bluemix.cloudant.com
export DB_USER2=85debada-fc80-4597-a913-ad1b699c3a5c-bluemix
export DB_PASS2='mypassword'
export DB_URL2='https://'$DB_USER2:$DB_PASS2@$DB_HOST2
```
But when running it I keep running into the following response: 
```
$ replicate-couchdb-cluster -s $DB_URL -t $DB_URL2
Fatal Error: getaddrinfo ENOTFOUND peteruithoven peteruithoven:443
```

**Comment by redgeoff** [comment]
Is it that you need to set DB_HOST to `peteruithoven.cloudant.com` and not
just `peteruithoven`?

**Comment by peteruithoven** [comment]
Good question, maybe I should have shared that part, but I think I'm doing that:
```
export DB_HOST=peteruithoven.cloudant.com
export DB_USER=peteruithoven
export DB_PASS="mypassword"
```

**Comment by redgeoff** [comment]
I was just able to replicate a cluster on cloudant with

    replicate-couchdb-cluster -s https://user1:secret1@db1.cloudant.com \
      -t https://user2:secret2@db2.cloudant.com

Your config looks good on the surface.

**Comment by redgeoff** [comment]
Closing as appeared to work in my tests
